# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App from the Azure Portal
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value
# 3. Update the AZURE_WEBAPP_NAME below with your actual Web App name
#
# Generated automatically by PowerShell script on 07/09/2025 22:17:01

name: Build and deploy Web App

env:
  AZURE_WEBAPP_NAME: VehiculoAPILunesWeb   # Change this to your Azure Web App name
  AZURE_WEBAPP_PACKAGE_PATH: 'Vehiculos.WEB/Web'
  DOTNET_VERSION: '8.0'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Vehiculos.WEB/Web/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
      - run: |
          cd "Vehiculos.WEB"
          dotnet restore "Abstracciones/*.csproj"
          dotnet restore "Reglas/*.csproj"
          dotnet restore "Web/*.csproj"

      - name: Build with dotnet
        run: |
          cd "Vehiculos.WEB"
          dotnet build "Abstracciones/*.csproj" --configuration Release --no-restore
          dotnet build "Reglas/*.csproj" --configuration Release --no-restore
          dotnet build "Web/*.csproj" --configuration Release --no-restore

      - name: Run tests
        run: dotnet test "Vehiculos.WEB/Vehiculos.WEB.sln" --no-restore --verbosity normal --configuration Release || echo "No tests found or test execution failed"

      - name: dotnet publish
        run: dotnet publish "Vehiculos.WEB/Web/*.csproj" -c Release -o ./publish --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPPWeb_PUBLISH_PROFILE }}
          package: .
          respect-funcignore: true
